### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by astaxie** [astaxie/beco#1]
- [x] toml config
- [ ] routing support http and https
- [ ] Auth 
- [ ] AntiBot
- [ ] Rate Limit
- [ ] monitoring
- [ ] Access Log
- [ ] Capturing and replaying live HTTP traffic into a test environment
- [ ] fault-tolerant (Circuit Breaker Patten)
- [ ] fallback  
- [ ] Router to etcd/consul interface

**Comment by astaxie** [comment]
* [ ] Router to etcd/consul interface
